Controllers films users
Alexander-Kuzin/java-filmorate pull request #3
Opened 2023-04-19 09:23 UTC by Alexander-Kuzin

2023-04-19 11:08 UTC, Frilock requested changes
Добрый день, оставил пару комментариев к работе

2023-04-19 11:08 UTC, Frilock commented on pom.xml
> +			<version>1.18.20</version>
Версии библиотек, которые вы подключаете в pom файле, принято указывать в properties, по аналогии с версией Java, а в поле version самой библиотеки указывать так ${example-lib.version}. Это нужно для того, чтобы версии библиотек находились в одном месте и их изменении проходило безболезненно.

2023-04-19 11:08 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Long id = 0L;
отсутствует приватный модификатор у поля

2023-04-19 11:08 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            if (user.getName() == null || user.getName().isBlank()) {
Вообще можно объединить эти обе проверки, используя утилиту из библиотеки apache common 3, StringUtils.isBlank(..), вообще там довольно много полезных методов

2023-04-19 11:08 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +@Slf4j
Лишняя аннотация

2023-04-19 11:08 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final HashMap<Long, User> users = new HashMap<>();
В значении лучше указывать интерфейс, а не реализацию =) Уже вроде проговаривали

2023-04-19 11:08 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private static ValidatorFactory validatorFactory = Validation.buildDefaultValidatorFactory();
Вообще как то вы ОЧЕНЬ усложнили валидацию в приложении. Вообще вроде Вам предложили воспользоваться двумя вариантами, либо самому руками написать проверки и проверить входной объект, либо воспользоваться валидацией от spring-boot-validation-starter, повесив аннотации на поля ДТОшки. Вы как то скомбинировали оба метода, плюс еще добавили валидацию из библиотеки

<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
			<version>2.0.1.Final</version>
		</dependency>
		
		Не скажу что это не правильно, но по моему Вы как то усложнили =) (зато приобрели дополнительные навыки)
		Но в целом, конечно, работает и ладно.

2023-04-19 13:03 UTC, Alexander-Kuzin commented on pom.xml
> +			<version>1.18.20</version>
В теории нам это не рассказывали, я не знал, спасибо!
При добавлении зависимостей копипастил с сайтов, теперь буду делать так!

2023-04-19 13:03 UTC, Alexander-Kuzin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Long id = 0L;
Поправил, спасибо!

2023-04-19 13:05 UTC, Alexander-Kuzin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            if (user.getName() == null || user.getName().isBlank()) {
Переделал! 
К другим методам тоже присмотрюсь!
Спасибо за совет!

2023-04-19 13:05 UTC, Alexander-Kuzin commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +@Slf4j
Убрал, спасибо!

2023-04-19 13:06 UTC, Alexander-Kuzin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final HashMap<Long, User> users = new HashMap<>();
Да, проговаривали, не знаю почему у меня рука дёргается в эту сторону периодически =) Буду внимательнее, спасибо!

2023-04-19 13:08 UTC, Alexander-Kuzin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private static ValidatorFactory validatorFactory = Validation.buildDefaultValidatorFactory();
Да, скорее соглашусь, чем возражу.
Мне ОЧЕНЬ хотелось реализовать собственные аннотации, поэтому и пошёл по такому тернистому, но интересному пути =)

2023-04-20 06:21 UTC, Frilock approved these changes
Принял

2023-04-20 06:21 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private Long id = 0L;
Еще можно статик добавить

2023-04-20 09:32 UTC, Alexander-Kuzin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private Long id = 0L;
Добавил сразу в двух контроллерах! Спасибо!
Отправил новый коммит [781898b]
Тесты успешно пройдены.

2023-04-20 15:30 UTC, merged