Sprint 11 - add-database - v.1
Alexander-Kuzin/java-filmorate pull request #5
Opened 2023-05-28 20:46 UTC by Alexander-Kuzin

2023-05-29 19:54 UTC, Frilock requested changes
Добрый день, я начал смотреть вашу работу, и хочется сразу отметить тот момент который мне очень не нравиться. На мой взгляд, не нужно неиспользуемый код помечать как Deprecated, или просто его закоментировать. Удаляйте его сразу, обычно Deprecated используют при переходе между версиями приложений, когда у Вас уже есть потребитель и ему нужно дать время на переход между новым и старым решением. В данном случае вам это не нужно. Удаляйте такой код.

Кроме того, следите за тем, чтобы просто так не расставлять аннотации. Например, я заметил, что у вас в некоторых местах стоят аннотации для логгирования, хотя его там нет.

Кроме того, когда в классы принято инжектить (внедрять) бины через интерфейс (комментарий указал), а не реализацию сразу. 

Поправьте эти моменты,пожалуйста, и присылайте снова.

2023-05-29 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/annotations/BirthDay.java
> +@Deprecated(since = "Sprint 10")
Если данные объекты не актуальны то лучше их удалить, не вижу смысла ставить Deprecated

2023-05-29 19:54 UTC, Frilock commented on pom.xml
> +<!--		<dependency>-->
Закомментированного кода в приложении быть не должно, либо уберите, либо оставьте

2023-05-29 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@Slf4j
Лишняя аннотация

2023-05-29 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +        return new ArrayList<>(genreService.getGenres());
Лучше просто return genreService.getGenres

2023-05-29 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +@Slf4j
Лишняя аннотация

2023-05-29 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/FilmNotFoundException.java
> +@Deprecated (since = "Sprint 10")
Зачем это? Удаляйте тогда

2023-05-29 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        this.likedFilms = new LinkedHashSet<>();
А почему Linked? Вам порядок важен? Почему не обычный HashSet&

2023-05-29 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +            if (genre.id == id) {
Обращаться к полю лучше так же через get

2023-05-29 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    /**
Излишний комментарий

2023-05-29 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +
Лишняя пустая строка

2023-05-29 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      private LocalDate birthday;
На мой взгляд, проще инициализировать сразу же (new HashSet) чтобы избежать проверки на нул для коллекций

2023-05-29 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/InMemoryFilmService.java
> +    private final InMemoryFilmStorage filmStorage;
Правильнее инжектить в класс интерфейс, а не реализацию, то есть в данном случае FilmStorage

2023-05-29 20:15 UTC, Alexander-Kuzin commented on src/main/java/ru/yandex/practicum/filmorate/annotations/BirthDay.java
> +@Deprecated(since = "Sprint 10")
Спасибо! Удалил!

2023-05-29 20:15 UTC, Alexander-Kuzin commented on pom.xml
> +<!--		<dependency>-->
Спасибо! Удалил!

2023-05-29 20:16 UTC, Alexander-Kuzin commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@Slf4j
Спасибо! Удалил!

2023-05-29 20:16 UTC, Alexander-Kuzin commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +@Slf4j
Спасибо! Удалил!

2023-05-29 20:16 UTC, Alexander-Kuzin commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/FilmNotFoundException.java
> +@Deprecated (since = "Sprint 10")
Удалил!

2023-05-29 20:17 UTC, Alexander-Kuzin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        this.likedFilms = new LinkedHashSet<>();
Поправил

2023-05-29 20:19 UTC, Alexander-Kuzin commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    /**
Удалил!

2023-05-29 20:22 UTC, Alexander-Kuzin commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +
Поправил

2023-05-29 20:26 UTC, Alexander-Kuzin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      private LocalDate birthday;
Я так понимаю тут подразумевается поле  private Set<Long> friendsId;
Собственно для него поправил, и убрал проверку на null.

2023-05-29 20:30 UTC, Alexander-Kuzin commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +        return new ArrayList<>(genreService.getGenres());
Поправил

2023-05-29 20:31 UTC, Alexander-Kuzin commented on src/main/java/ru/yandex/practicum/filmorate/service/InMemoryFilmService.java
> +    private final InMemoryFilmStorage filmStorage;
Принято, спасибо

2023-05-30 12:40 UTC, Frilock requested changes
Добрый день, к запросам вопросов у меня нет, но есть ряд мелких комментариев. Посмотрите пожалуйста

2023-05-30 12:40 UTC, Frilock commented on pom.xml
> +    <dependencies>
Лучше между тегами зависимостей и версий 1 строчку пропустить, чтоб не сливалось.

2023-05-30 12:40 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        this.genres = new LinkedHashSet<>();
Опять же вопрос, а почему LinkedHashSet?

2023-05-30 12:40 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      private LocalDate birthday;
Вообще я имел ввиду все коллекции в ваших классах моделей, а не только friendsId

2023-05-30 12:40 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +public interface GenreService {
Интерфейсы GenreService  и MpaService вообще являются одинаковыми, кроме типа данных, можно сделать абстрактный класс для общий интерфейс или даже абстрактный класс с общей логикой. 
Задача со звездочкой =) Если хотите конечно

2023-05-30 12:40 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbFilmStorageImpl.java
> +        jdbcTemplate.batchUpdate(sqlQueryAddLikes, new BatchPreparedStatementSetter() {
Данная логика повторяется во многих методах, ее лучше вынести в отдельный метод

2023-05-30 12:40 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbUserStorageImpl.java
> +        assert user != null;
assert на практике используется крайне мало, предлагаю заменить на requiredNotNull

2023-05-30 12:40 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/Mapper.java
> +                resultSet.getDate("releaseDate").toLocalDate(),
resultSet.getDate("releaseDate") а тут null никогда не вернется?

2023-05-30 12:40 UTC, Frilock commented on src/main/resources/sql/schema.sql
> +CREATE TABLE IF NOT EXISTS public.users (user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
После Drop нужно 1 строку пропустить

2023-05-30 12:40 UTC, Frilock commented on src/main/resources/sql/schema.sql
> +CREATE TABLE IF NOT EXISTS public.users (user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
public. можно не указывать, так как public это дефолтная схема

2023-05-30 12:40 UTC, Frilock commented on src/main/resources/sql/schema.sql
> +CREATE TABLE IF NOT EXISTS public.users (user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
Кроме того, давайте сделаем одинаковое форматирование для скриптов создания таблиц.

2023-05-30 12:40 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +@SpringBootTest()
() не нужны

2023-05-30 12:40 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
>  class FilmorateApplicationTests {
Все же был более приятный вариант, когда тесты для разных сущностей находятся в разных тестовых классах, это делает их меньше и проще. В целом так тоже допустимо

2023-05-30 13:03 UTC, Alexander-Kuzin commented on pom.xml
> +    <dependencies>
Спасибо, добавил

2023-05-30 13:06 UTC, Alexander-Kuzin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        this.genres = new LinkedHashSet<>();
поправил

2023-05-30 13:27 UTC, Alexander-Kuzin commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/Mapper.java
> +                resultSet.getDate("releaseDate").toLocalDate(),
Поправьте меня, если я ошибаюсь, но аннотация @NotNull  у поля releaseDate защищает значение поля класса от null.
В конкретно этом участке кода, работа ведётся с данными, полученными уже из БД, которые первоначально туда попали из объекта, поле которого помечено указанной  аннотацией.

2023-05-30 14:07 UTC, Alexander-Kuzin commented on src/main/resources/sql/schema.sql
> +CREATE TABLE IF NOT EXISTS public.users (user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
public убрал, остальное отформатировал

2023-05-30 14:07 UTC, Alexander-Kuzin commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +@SpringBootTest()
спасибо, убрал

2023-05-30 14:33 UTC, Alexander-Kuzin commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
>  class FilmorateApplicationTests {
Реализовал более приятный вариант =)

2023-05-30 14:37 UTC, Alexander-Kuzin commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbUserStorageImpl.java
> +        assert user != null;
Применил

2023-05-30 19:14 UTC, Frilock approved these changes
Принято

2023-06-05 10:52 UTC, merged